name: Next.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: src/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: ./src

      - name: Build Next.js
        run: npm run build
        working-directory: ./src

      - name: Upload .next as artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: src/.next   # путь из корня!
      - name: Check working directory
        run: pwd && ls -la

      - name: Find .next folder
        run: find . -maxdepth 3 -type d -name ".next"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: src/.next

      - name: Build Docker image
        run: docker build -t nextjs-test .

      - name: Run container
        run: docker run -d -p 3000:3000 --name nextjs-app nextjs-test